services:
  - type: web
    name: sp500-earnings-calendar
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FMP_API_KEY
        sync: false 