services:
  - type: web
    name: sp500-earnings-calendar
    env: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --threads 2
    envVars:
      - key: FMP_API_KEY
        sync: false 